'use strict';
const $=s=>document.querySelector(s),canvas=$('#arena'),ctx=canvas.getContext('2d');
const skins=[{name:'Классика',color:'#05c6e7',symbol:''},{name:'Мандарин',color:'#ffaa4b',symbol:''},{name:'Лаванда',color:'#aa7cf0',symbol:''},{name:'Мята',color:'#45d6a8',symbol:''},{name:'Котик',color:'#f4aa66',symbol:'🐱'},{name:'Панда',color:'#8997ae',symbol:'🐼'},{name:'Арбуз',color:'#ee7da0',symbol:'🍉'},{name:'Космос',color:'#7876dc',symbol:'✦'}];
const trailTypes=[['Лента','Чистая классика',''],['Пунктир','Лёгкий ритм','dashes'],['Искры','Сияй на всей арене','sparkles'],['Радуга','Больше цвета','rainbow']];
function read(){try{return JSON.parse(localStorage.getItem('paper-io-save')||'{}')}catch{return{}}}
let prefs={skin:0,trail:0,name:'Игрок',difficulty:'normal',best:0,games:0,kills:0,...read()};prefs.skin=Math.max(0,Math.min(7,+prefs.skin||0));prefs.trail=Math.max(0,Math.min(3,+prefs.trail||0));
function save(){try{localStorage.setItem('paper-io-save',JSON.stringify(prefs))}catch{}}
let game=null,W=innerWidth,H=innerHeight,dpr=1,last=0,time=0,cam={x:50,y:50},view={cell:25,x:0,y:0},toastTimer=0,manual=false,lastFocus=null;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const renderer=new PaperRenderer(ctx);
function menuScene(){renderer.menu(W,H,time)}
function drawGame(dt){renderer.draw(game,W,H,dt,skins[prefs.skin],prefs.trail,time);view=renderer.view}
function updateHud(){if(!game)return;const a=game.actors[0];$('#percentage').innerHTML=game.percent(a).toFixed(2)+'<small>%</small>';$('#score-fill').style.width=game.percent(a)+'%';$('#kills').textContent='✦ '+game.kills;$('#timer').textContent=formatTime(game.elapsed);const sorted=game.actors.filter(a=>a.alive).sort((a,b)=>b.cells-a.cells);$('#leaders').replaceChildren(...sorted.slice(0,6).map((b,i)=>{const li=document.createElement('li');if(b.id===1)li.className='me';const rank=document.createElement('span');rank.className='rank';rank.textContent=i+1;const dot=document.createElement('span');dot.className='dot';dot.style.background=b.color;const name=document.createElement('span');name.className='name';name.textContent=b.name;const p=document.createElement('span');p.className='percent';p.textContent=game.percent(b).toFixed(2)+'%';li.append(rank,dot,name,p);return li}))}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}
function refreshPrefs(){const s=skins[prefs.skin];document.documentElement.style.setProperty('--skin',s.color);document.documentElement.style.setProperty('--skin-dark',s.color);$('#preview-cube span').textContent=s.symbol;$('#best-label').textContent='Лучший результат: '+(+prefs.best).toFixed(2)+'%';$('#nickname').value=prefs.name;$('#difficulty').value=prefs.difficulty;save()}
function toast(text){$('#capture-toast').textContent=text;$('#capture-toast').classList.add('show');toastTimer=1.6}
function start(){prefs.name=$('#nickname').value.trim()||'Игрок';prefs.difficulty=$('#difficulty').value;save();hideModal(false);game=new PaperGame({name:prefs.name,color:skins[prefs.skin].color,skin:prefs.skin,difficulty:prefs.difficulty,onToast:toast,onImpact:amount=>renderer.impact(amount),onEnd:finish});cam={x:50,y:50};renderer.reset(game);held.clear();pointerTarget=null;$('#menu').classList.add('hidden');$('#footer').classList.add('hidden');$('#hud').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#records').classList.add('hidden');updateHud();canvas.focus()}
function home(){if(game&&!game.recorded){prefs.best=Math.max(prefs.best,game.peak);prefs.games++;prefs.kills+=game.kills;save()}game=null;hideModal(false);$('#menu').classList.remove('hidden');$('#footer').classList.remove('hidden');$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#records').classList.remove('hidden');refreshPrefs()}
function showModal(title,content,closable=true){lastFocus=document.activeElement;$('#modal-title').textContent=title;$('#modal-content').innerHTML=content;$('#modal').classList.remove('hidden');$('#close-modal').classList.toggle('hidden',!closable);const focus=$('#modal').querySelector('button:not(.hidden)');focus?.focus()}
function hideModal(resume=true){$('#modal').classList.add('hidden');if(resume&&game?.mode==='paused')game.mode='playing';lastFocus?.focus()}
function finish(reason){game.recorded=true;prefs.games++;prefs.kills+=game.kills;const isRecord=game.peak>prefs.best;prefs.best=Math.max(prefs.best,game.peak);save();const ended=game;setTimeout(()=>{if(game!==ended)return;showModal(game.mode==='won'?'Арена твоя!':isRecord?'Новый рекорд!':'Ещё один раунд?',`<p class="sub" id="end-reason"></p><div class="result-stats"><div><b>${game.peak.toFixed(2)}%</b><span>ТЕРРИТОРИЯ</span></div><div><b>${game.kills}</b><span>УСТРАНЕНО</span></div><div><b>${formatTime(game.elapsed)}</b><span>ВРЕМЯ</span></div></div><button id="restart" class="primary done">ИГРАТЬ ЕЩЁ</button><button id="back-home" class="secondary">В главное меню</button>`,false);$('#end-reason').textContent=reason;$('#restart').onclick=start;$('#back-home').onclick=home},600)}
function pause(){if(!game)return;if(game.mode==='paused'){hideModal();return}if(game.mode!=='playing')return;game.mode='paused';showModal('Небольшая пауза',`<p class="sub">Твоя территория подождёт.</p><button id="resume" class="primary done">ПРОДОЛЖИТЬ</button><button id="back-home" class="secondary">В главное меню</button>`);$('#resume').onclick=()=>hideModal();$('#back-home').onclick=home}
function showSkins(){showModal('Выбери свой стиль','<p class="sub">Маленький кубик. Большой характер.</p><div class="skin-grid"></div><button class="primary done" id="done">ГОТОВО</button>');const grid=$('.skin-grid');skins.forEach((s,i)=>{const b=document.createElement('button');b.className='skin-option'+(prefs.skin===i?' selected':'');b.setAttribute('aria-pressed',prefs.skin===i);b.innerHTML=`<span class="mini-cube" style="--color:${s.color}">${s.symbol}</span>${s.name}`;b.onclick=()=>{prefs.skin=i;refreshPrefs();showSkins()};grid.append(b)});$('#done').onclick=()=>hideModal()}
function showTrails(){showModal('Оставь свой след','<p class="sub">Твой путь к новым территориям.</p><div id="trail-list"></div><button class="primary done" id="done">ГОТОВО</button>');trailTypes.forEach(([name,sub,type],i)=>{const b=document.createElement('button');b.className='trail-option'+(prefs.trail===i?' selected':'');b.setAttribute('aria-pressed',prefs.trail===i);b.innerHTML=`<span class="trail-swatch ${type}"></span><span><strong>${name}</strong><small>${sub}</small></span>`;b.onclick=()=>{prefs.trail=i;save();showTrails()};$('#trail-list').append(b)});$('#done').onclick=()=>hideModal()}
$('#start-btn').onclick=start;$('#skins-btn').onclick=showSkins;$('#trails-btn').onclick=showTrails;$('#pause').onclick=pause;$('#close-modal').onclick=()=>hideModal();$('#brand').onclick=e=>{e.preventDefault();if(game?.mode==='playing')pause();else if(!game)home()};$('#records').onclick=()=>showModal('Твои рекорды',`<p class="sub">Каждая новая территория — маленькая победа.</p><div class="big-record">${(+prefs.best).toFixed(2)}%</div><p class="record-caption">ЛУЧШИЙ ЗАХВАТ АРЕНЫ</p><div class="result-stats"><div><b>${prefs.games}</b><span>ИГР</span></div><div><b>${prefs.kills}</b><span>УСТРАНЕНО</span></div><div><b>8</b><span>СКИНОВ</span></div></div>`);
$('#help-btn').onclick=()=>showModal('Как играть',`<p class="sub">Расширяй границы. Береги свой след.</p><div class="help-row"><b>01</b><div><strong>Управляй кубиком</strong><span>Мышь задаёт любое направление. WASD и стрелки поддерживают диагонали. На телефоне веди пальцем по арене. Повороты плавные, без привязки к клеткам.</span></div></div><div class="help-row"><b>02</b><div><strong>Замкни контур</strong><span>Выйди за свою территорию и вернись на неё — всё внутри контура станет твоим.</span></div></div><div class="help-row"><b>03</b><div><strong>Перережь чужой след</strong><span>Устраняй ботов, пока они снаружи. Береги свой след: пересечение с ним и выход за границы завершают игру.</span></div></div><p class="sub" style="margin:20px 0 0">Esc / P — пауза · F — полный экран.<br>Захвати 90% арены, чтобы победить.</p>`);
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Полный экран недоступен в этом окне')}}$('#fullscreen').onclick=fullscreen;
const keys={ArrowRight:0,d:0,D:0,в:0,В:0,ArrowDown:1,s:1,S:1,ы:1,Ы:1,ArrowLeft:2,a:2,A:2,ф:2,Ф:2,ArrowUp:3,w:3,W:3,ц:3,Ц:3};
const held=new Set();let pointerTarget=null;
function keyboardDirection(){let x=0,y=0;for(const d of held){x+=[1,0,-1,0][d];y+=[0,1,0,-1][d]}if(x||y){pointerTarget=null;game?.steerAngle(Math.atan2(y,x))}}
addEventListener('keydown',e=>{if(e.key==='Tab'&&!$('#modal').classList.contains('hidden')){const buttons=[...$('#modal').querySelectorAll('button:not(.hidden)')];const first=buttons[0],end=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus()}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus()}return}if(e.target.matches('input,select')){if(e.key==='Enter'&&e.target.id==='nickname')start();return}if(e.key==='Escape'){if(game?.mode==='playing'||game?.mode==='paused')pause();else if(!$('#close-modal').classList.contains('hidden'))hideModal();return}if(e.key.toLowerCase()==='f')fullscreen();if(e.key.toLowerCase()==='p')pause();if(game?.mode==='playing'&&keys[e.key]!==undefined){e.preventDefault();held.add(keys[e.key]);keyboardDirection()}});
addEventListener('keyup',e=>{if(keys[e.key]!==undefined){held.delete(keys[e.key]);if(game?.mode==='playing')keyboardDirection()}});
addEventListener('blur',()=>held.clear());
function pointer(e){if(game?.mode!=='playing')return;held.clear();pointerTarget={x:e.clientX,y:e.clientY};aimPointer()}
function aimPointer(){if(!pointerTarget||game?.mode!=='playing')return;const a=game.actors[0],x=view.x+a.x*view.cell,y=view.y+a.y*view.cell,dx=pointerTarget.x-x,dy=pointerTarget.y-y;if(Math.hypot(dx,dy)>24)game.steerAngle(Math.atan2(dy,dx))}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointer(e)});canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch')pointerTarget=null});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.mode==='playing')pause()});
function update(dt){time+=dt;aimPointer();if(game)game.update(dt);if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#capture-toast').classList.remove('show')}}
function draw(dt=1/60){ctx.setTransform(dpr,0,0,dpr,0,0);if(game)drawGame(dt);else menuScene()}
let hudClock=0;function frame(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;if(!manual)update(dt);draw(dt);hudClock+=dt;if(hudClock>.15){updateHud();hudClock=0}requestAnimationFrame(frame)}
window.render_game_to_text=()=>JSON.stringify(game?{...game.state(),skin:skins[prefs.skin].name,trail:trailTypes[prefs.trail][0]}:{mode:'menu',skin:skins[prefs.skin].name,trail:trailTypes[prefs.trail][0],best:prefs.best});window.advanceTime=ms=>{manual=true;for(let n=0;n<Math.ceil(ms/(1000/60));n++)update(1/60);draw();updateHud()};refreshPrefs();requestAnimationFrame(frame);

