/* Continuous world-space movement. A fine hidden mask is used only to fill territory. */
(function(global){
'use strict';
const N=240,WORLD=100,S=N/WORLD,TAU=Math.PI*2;
const COLORS=['#00c9e8','#ffa44b','#a575f0','#37d7ac','#f66a9e','#5e8cf6','#efc345','#ed7962','#78c77a','#9685d5'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const delta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
function segmentDistance(x,y,p,q){const dx=q.x-p.x,dy=q.y-p.y,l=dx*dx+dy*dy,t=l?clamp(((x-p.x)*dx+(y-p.y)*dy)/l,0,1):0;return Math.hypot(x-p.x-t*dx,y-p.y-t*dy)}
class PaperGame{
 constructor(options={}){this.options=options;this.resolution=N;this.grid=new Uint8Array(N*N);this.actors=[];this.particles=[];this.rings=[];this.captures=[];this.elapsed=0;this.mode='playing';this.kills=0;this.peak=0;this.version=0;this.seed=options.seed||Date.now()%2147483647;this.difficulty=options.difficulty||'normal';this.speed=6.8;this.thinkClock=0;this.init()}
 random(){this.seed=this.seed*16807%2147483647;return(this.seed-1)/2147483646}
 index(x,y){return clamp(Math.floor(y*S),0,N-1)*N+clamp(Math.floor(x*S),0,N-1)}
 owner(x,y){return this.grid[this.index(x,y)]}
 percent(a){return a.cells/(N*N)*100}
 init(){[[50,50],[32,35],[70,34],[73,62],[32,69],[51,21],[53,81],[17,50],[86,44],[22,19]].forEach(([x,y],i)=>this.spawn(i,x,y));this.count()}
 spawn(i,x,y){const a={id:i+1,x,y,px:x,py:y,angle:i*1.9,targetAngle:i*1.9,alive:true,color:i===0?(this.options.color||COLORS[0]):COLORS[i],name:i===0?(this.options.name||'Игрок'):['','Luna','Mango','Minty','Pixel','Orbit','Sunny','Fox','Kiwi','Nova'][i],trail:[],pathLength:0,plan:[],cells:0,shield:this.elapsed+2,respawn:0,skin:i===0?(this.options.skin||0):0,think:0,home:{x,y},wake:[],bank:0};this.actors[i]=a;this.paintDisk(x,y,3.7,a.id);this.version++;return a}
 paintDisk(x,y,r,id){const x0=clamp(Math.floor((x-r)*S),0,N-1),x1=clamp(Math.ceil((x+r)*S),0,N-1),y0=clamp(Math.floor((y-r)*S),0,N-1),y1=clamp(Math.ceil((y+r)*S),0,N-1);for(let iy=y0;iy<=y1;iy++)for(let ix=x0;ix<=x1;ix++)if(Math.hypot((ix+.5)/S-x,(iy+.5)/S-y)<=r)this.grid[iy*N+ix]=id}
 steer(dir){this.steerAngle(dir*Math.PI/2)}
 steerAngle(angle){if(this.actors[0].alive)this.actors[0].targetAngle=angle}
 count(){for(const a of this.actors)a.cells=0;for(const id of this.grid)if(id)this.actors[id-1].cells++;this.peak=Math.max(this.peak,this.percent(this.actors[0]))}
 nearestHome(a){let best=null,dist=Infinity;for(let y=1;y<N-1;y+=3)for(let x=1;x<N-1;x+=3){const j=y*N+x;if(this.grid[j]!==a.id)continue;const wx=(x+.5)/S,wy=(y+.5)/S,d=(wx-a.x)**2+(wy-a.y)**2;if(d<dist){dist=d;best={x:wx,y:wy}}}return best||a.home}
 hitsTrail(a,x,y,margin=.55,ignoreRecent=true){if(a.trail.length<2)return false;const cutoff=ignoreRecent?a.pathLength-2.2:Infinity;for(let k=1;k<a.trail.length;k++){const p=a.trail[k-1],q=a.trail[k];if(q.d>cutoff)break;if(segmentDistance(x,y,p,q)<margin)return true}return false}
 bot(a,dt){a.think-=dt;if(a.think>0)return;a.think=.15+this.random()*.12;const home=this.owner(a.x,a.y)===a.id;let danger=false;if(a.trail.length>8){for(const b of this.actors)if(b!==a&&b.alive){for(let k=0;k<a.trail.length;k+=5)if(Math.hypot(b.x-a.trail[k].x,b.y-a.trail[k].y)<4){danger=true;break}}}if(danger||a.pathLength>37){a.plan=[this.nearestHome(a)]}
 if(!a.plan.length){if(!home)a.plan=[this.nearestHome(a)];else{const ag=this.difficulty==='hard'?.5:this.difficulty==='normal'?.2:.04;let target=null,dist=12;if(this.random()<ag)for(const b of this.actors)if(b!==a&&b.alive)for(let k=0;k<b.trail.length-10;k+=5){const p=b.trail[k],d=Math.hypot(p.x-a.x,p.y-a.y);if(d<dist){dist=d;target={x:p.x,y:p.y}}}if(target)a.plan=[target,a.home];else{a.home={x:a.x,y:a.y};const angle=a.angle+(this.random()-.5)*1.6,l=7+this.random()*7,side=this.random()<.5?1:-1,dx=Math.cos(angle),dy=Math.sin(angle),nx=-dy*side,ny=dx*side;const point=(f,s)=>({x:clamp(a.x+dx*f+nx*s,5,95),y:clamp(a.y+dy*f+ny*s,5,95)});a.plan=[point(l,0),point(l+1,5),point(1,7),point(0,0)]}}}
 while(a.plan.length&&Math.hypot(a.plan[0].x-a.x,a.plan[0].y-a.y)<1.5)a.plan.shift();let desired=a.plan.length?Math.atan2(a.plan[0].y-a.y,a.plan[0].x-a.x):a.angle;let best=desired,bestCost=Infinity;for(const offset of [0,.45,-.45,.9,-.9,1.4,-1.4,2,-2,Math.PI]){const dir=desired+offset;let cost=Math.abs(offset)*.6+Math.abs(delta(a.angle,dir))*.13;for(const r of [1.1,2.1,3.2]){const x=a.x+Math.cos(dir)*r,y=a.y+Math.sin(dir)*r;if(x<1.5||y<1.5||x>98.5||y>98.5)cost+=50;if(this.hitsTrail(a,x,y,.95))cost+=30;for(const b of this.actors)if(b!==a&&b.alive&&Math.hypot(b.x-x,b.y-y)<1.5&&this.owner(x,y)!==a.id)cost+=7}if(cost<bestCost){bestCost=cost;best=dir}}a.targetAngle=best}
 burst(x,y,color,n=24,power=1){for(let i=0;i<n;i++){const angle=this.random()*TAU,v=(1+this.random()*5)*power;this.particles.push({x,y,vx:Math.cos(angle)*v,vy:Math.sin(angle)*v,life:.4+this.random()*.8,max:1.2,color,size:.06+this.random()*.18,spin:this.random()*6,type:i%4===0?'star':'square'})}}
 kill(a,killer,reason){if(!a.alive)return;a.alive=false;a.respawn=this.elapsed+3;for(let j=0;j<N*N;j++)if(this.grid[j]===a.id)this.grid[j]=0;this.version++;this.burst(a.x,a.y,a.color,48,1.6);this.rings.push({x:a.x,y:a.y,color:a.color,life:1,max:1,size:5});a.trail=[];if(killer&&killer!==a&&killer.id===1){this.kills++;this.options.onToast?.('Соперник устранён!');this.options.onImpact?.(.8)}if(a.id===1){this.mode='over';this.count();this.options.onImpact?.(1.3);this.options.onEnd?.(reason)}}
 capture(a){if(a.trail.length<2)return;const before=a.cells;for(let k=1;k<a.trail.length;k++){const p=a.trail[k-1],q=a.trail[k],steps=Math.ceil(Math.hypot(q.x-p.x,q.y-p.y)*S*2);for(let s=0;s<=steps;s++){const t=steps?s/steps:0;this.paintDisk(p.x+(q.x-p.x)*t,p.y+(q.y-p.y)*t,.48,a.id)}}const seen=new Uint8Array(N*N),q=new Int32Array(N*N);let head=0,tail=0;const push=j=>{if(!seen[j]&&this.grid[j]!==a.id){seen[j]=1;q[tail++]=j}};for(let n=0;n<N;n++){push(n);push((N-1)*N+n);push(n*N);push(n*N+N-1)}while(head<tail){const j=q[head++],x=j%N,y=Math.floor(j/N);if(x)push(j-1);if(x<N-1)push(j+1);if(y)push(j-N);if(y<N-1)push(j+N)}const captured=[];for(let j=0;j<N*N;j++)if(!seen[j]&&this.grid[j]!==a.id){this.grid[j]=a.id;if(j%9===0)captured.push(j)}this.captures.push({id:a.id,life:.7,max:.7,cells:captured});const trail=a.trail;this.rings.push({x:a.x,y:a.y,color:a.color,life:.8,max:.8,size:4});for(let i=0;i<trail.length;i+=Math.max(1,Math.floor(trail.length/12)))this.burst(trail[i].x,trail[i].y,a.color,2,.55);a.trail=[];a.pathLength=0;a.plan=[];a.home={x:a.x,y:a.y};this.version++;this.count();const added=(a.cells-before)/(N*N)*100;if(a.id===1&&added>.015){this.options.onToast?.('+'+added.toFixed(2)+'% территории');this.options.onImpact?.(.16);this.burst(a.x,a.y,a.color,28)}for(const b of this.actors)if(b.alive&&b!==a&&b.cells===0)this.kill(b,a,'Твоя территория захвачена');if(a.id===1&&this.percent(a)>=90){this.mode='won';this.options.onEnd?.('Ты покорил арену!')}}
 step(dt){this.elapsed+=dt;for(const a of this.actors){if(this.mode!=='playing')break;if(!a.alive){if(a.id>1&&this.elapsed>a.respawn){let found=false;for(let i=0;i<40;i++){const x=7+this.random()*86,y=7+this.random()*86;if(!this.owner(x,y)&&this.actors.every(b=>!b.alive||Math.hypot(b.x-x,b.y-y)>12)){this.spawn(a.id-1,x,y);found=true;break}}if(!found)a.respawn=this.elapsed+1}continue}if(a.id>1)this.bot(a,dt);const change=clamp(delta(a.angle,a.targetAngle),-4.6*dt,4.6*dt);a.angle+=change;a.bank+=(change/dt*.07-a.bank)*Math.min(1,dt*8);a.px=a.x;a.py=a.y;const speed=this.speed*(a.id===1?1:this.difficulty==='easy'?.78:this.difficulty==='hard'?1.01:.91);a.x+=Math.cos(a.angle)*speed*dt;a.y+=Math.sin(a.angle)*speed*dt;if(a.x<.6||a.x>99.4||a.y<.6||a.y>99.4){this.kill(a,null,'Ты вышел за границу арены');continue}if(a.shield<this.elapsed){if(this.hitsTrail(a,a.x,a.y,.58)){this.kill(a,a,'Ты пересёк собственный след');continue}for(const b of this.actors)if(b!==a&&b.alive&&b.shield<this.elapsed){if(this.hitsTrail(b,a.x,a.y,.75,false))this.kill(b,a,'Соперник перерезал твой след');else if(Math.hypot(a.x-b.x,a.y-b.y)<.8){const owner=this.owner(a.x,a.y);if(owner===a.id)this.kill(b,a,'Столкновение на чужой территории');else if(owner===b.id)this.kill(a,b,'Столкновение на чужой территории');else{this.kill(b,a,'Лобовое столкновение');this.kill(a,b,'Лобовое столкновение')}}}}if(!a.alive)continue;const home=this.owner(a.x,a.y)===a.id;if(home){if(a.trail.length){a.pathLength+=Math.hypot(a.x-a.px,a.y-a.py);a.trail.push({x:a.x,y:a.y,d:a.pathLength});this.capture(a)}}else{if(!a.trail.length){a.pathLength=0;a.trail.push({x:a.px,y:a.py,d:0})}a.pathLength+=Math.hypot(a.x-a.px,a.y-a.py);const last=a.trail.at(-1);if(Math.hypot(last.x-a.x,last.y-a.y)>.15)a.trail.push({x:a.x,y:a.y,d:a.pathLength})}a.wake.push({x:a.x,y:a.y,life:.4});a.wake=a.wake.filter(p=>(p.life-=dt)>0);if(a.id===1&&a.trail.length&&this.random()<dt*20)this.particles.push({x:a.x,y:a.y,vx:(this.random()-.5)*1.8,vy:(this.random()-.5)*1.8,life:.35,max:.35,color:a.color,size:.05+this.random()*.08,type:'spark'})}}
 update(dt){if(this.mode==='paused')return;for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-dt*2);p.vy*=Math.exp(-dt*2);p.life-=dt}this.particles=this.particles.filter(p=>p.life>0);for(const r of this.rings)r.life-=dt;this.rings=this.rings.filter(r=>r.life>0);for(const c of this.captures)c.life-=dt;this.captures=this.captures.filter(c=>c.life>0);if(this.mode!=='playing')return;const steps=Math.max(1,Math.ceil(dt/(1/120)));for(let s=0;s<steps&&this.mode==='playing';s++)this.step(dt/steps);this.thinkClock+=dt;if(this.thinkClock>.4){this.count();this.thinkClock=0}}
 state(){const a=this.actors[0];return{mode:this.mode,coordinates:'continuous 100×100 world; origin top-left; x right, y down; angle radians',player:{x:+a.x.toFixed(3),y:+a.y.toFixed(3),angle:+a.angle.toFixed(3),targetAngle:+a.targetAngle.toFixed(3),alive:a.alive,territory:+this.percent(a).toFixed(3),trailLength:+a.pathLength.toFixed(2),trail:a.trail.filter((_,i)=>i%10===0).map(p=>[+p.x.toFixed(2),+p.y.toFixed(2)])},kills:this.kills,peak:+this.peak.toFixed(3),time:+this.elapsed.toFixed(2),bots:this.actors.slice(1).map(b=>({name:b.name,x:+b.x.toFixed(2),y:+b.y.toFixed(2),alive:b.alive,territory:+this.percent(b).toFixed(2),trailLength:+b.pathLength.toFixed(1)}))}}
}
global.PaperGame=PaperGame;global.PAPER_COLORS=COLORS;
})(typeof window!=='undefined'?window:globalThis);
