/* Smooth contour rendering, glossy characters, animated ribbons and particles. */
class PaperRenderer {
 constructor(ctx){this.ctx=ctx;this.land=document.createElement('canvas');this.land.width=this.land.height=1800;this.lctx=this.land.getContext('2d');this.version=-1;this.game=null;this.paths=[];this.camera={x:50,y:50};this.shake=0;this.zoom=1;this.view={cell:25,x:0,y:0};this.time=0;this.pointer=null;this.reduce=matchMedia('(prefers-reduced-motion: reduce)').matches}
 reset(game){this.game=game;this.version=-1;this.camera={x:50,y:50};this.zoom=1.08;this.shake=0}
 impact(amount){if(!this.reduce)this.shake=Math.max(this.shake,amount)}
 contours(game){const N=game.resolution,edges=Array.from({length:11},()=>new Map()),key=(x,y)=>y*(N+1)+x;const add=(id,x,y,xx,yy)=>{const k=key(x,y),map=edges[id];if(!map.has(k))map.set(k,[]);map.get(k).push(key(xx,yy))};for(let y=0;y<N;y++)for(let x=0;x<N;x++){const j=y*N+x,id=game.grid[j];if(!id)continue;if(y===0||game.grid[j-N]!==id)add(id,x,y,x+1,y);if(x===N-1||game.grid[j+1]!==id)add(id,x+1,y,x+1,y+1);if(y===N-1||game.grid[j+N]!==id)add(id,x+1,y+1,x,y+1);if(x===0||game.grid[j-1]!==id)add(id,x,y+1,x,y)}const paths=[];for(let id=1;id<=10;id++){const map=edges[id],path=new Path2D(),scale=100/N;while(map.size){const start=map.keys().next().value;let current=start;let points=[];let safety=0;do{points.push({x:current%(N+1)*scale,y:Math.floor(current/(N+1))*scale});const choices=map.get(current);if(!choices)break;const next=choices.pop();if(!choices.length)map.delete(current);current=next}while(current!==start&&++safety<N*N*4);if(points.length<3)continue;points=points.map((p,i,arr)=>{let x=0,y=0;for(let k=-3;k<=3;k++){const q=arr[(i+k+arr.length)%arr.length];x+=q.x;y+=q.y}return{x:x/7,y:y/7}});const p0=points[0],pn=points.at(-1);path.moveTo((p0.x+pn.x)/2,(p0.y+pn.y)/2);for(let k=0;k<points.length;k++){const p=points[k],q=points[(k+1)%points.length];path.quadraticCurveTo(p.x,p.y,(p.x+q.x)/2,(p.y+q.y)/2)}path.closePath()}paths[id]=path}return paths}
 cache(game){this.paths=this.contours(game);const c=this.lctx;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,1800,1800);c.scale(18,18);for(const a of game.actors){const path=this.paths[a.id];c.save();c.shadowColor=a.color+'46';c.shadowBlur=15;c.shadowOffsetY=6;const fill=c.createLinearGradient(0,0,55,100);fill.addColorStop(0,this.mix(a.color,'#ffffff',.48));fill.addColorStop(1,this.mix(a.color,'#ffffff',.12));c.fillStyle=fill;c.fill(path,'evenodd');c.shadowColor='transparent';c.lineWidth=.16;c.strokeStyle=a.color+'c0';c.stroke(path);c.clip(path,'evenodd');c.translate(0,.15);c.strokeStyle='#ffffff5c';c.lineWidth=.14;c.stroke(path);c.restore()}this.version=game.version}
 mix(hex,other,t){const a=parseInt(hex.slice(1),16),b=parseInt(other.slice(1),16);const v=s=>Math.round(((a>>s)&255)*(1-t)+((b>>s)&255)*t);return`rgb(${v(16)},${v(8)},${v(0)})`}
 rounded(c,x,y,w,h,r,fill){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill()}
 cube(c,x,y,s,color,symbol='',angle=0,bank=0,time=0){c.save();c.translate(x,y);c.rotate(angle+Math.PI/4+bank*.15);const bob=Math.sin(time*5)*s*.035;c.save();c.scale(1,.72);c.fillStyle='#17304725';c.filter='blur(5px)';c.beginPath();c.ellipse(0,s*.6,s*.66,s*.42,0,0,Math.PI*2);c.fill();c.restore();c.translate(0,-s*.16+bob);const side=c.createLinearGradient(-s*.5,0,s*.5,s*.7);side.addColorStop(0,this.mix(color,'#123453',.18));side.addColorStop(1,this.mix(color,'#123453',.4));this.rounded(c,-s*.5,-s*.3,s,s*.96,s*.23,side);const top=c.createLinearGradient(-s*.4,-s*.5,s*.5,s*.5);top.addColorStop(0,this.mix(color,'#ffffff',.44));top.addColorStop(.42,color);top.addColorStop(1,this.mix(color,'#ffffff',.12));c.shadowColor=color+'55';c.shadowBlur=s*.32;this.rounded(c,-s*.5,-s*.5,s,s*.84,s*.22,top);c.shadowBlur=0;c.lineWidth=1.25;c.strokeStyle='#ffffff68';c.beginPath();c.moveTo(-s*.29,-s*.44);c.quadraticCurveTo(-s*.43,-s*.43,-s*.44,-s*.28);c.lineTo(-s*.44,s*.05);c.stroke();if(symbol){c.rotate(-angle-Math.PI/4-bank*.15);c.font=`${s*.57}px 'Segoe UI Emoji',sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillStyle='#fff';c.fillText(symbol,0,-s*.07)}else{this.rounded(c,s*.1,-s*.34,s*.2,s*.13,s*.035,'#ffffffe8');c.fillStyle='#ffffff46';c.beginPath();c.ellipse(-s*.19,-s*.25,s*.16,s*.065,-.6,0,Math.PI*2);c.fill()}c.restore()}
 draw(game,W,H,dt,skin,trail,time){this.time=time;const c=this.ctx;if(this.game!==game)this.reset(game);if(this.version!==game.version)this.cache(game);const a=game.actors[0];this.zoom+=(1-this.zoom)*Math.min(1,dt*3);const follow=this.reduce?1:1-Math.exp(-dt*7);const ahead=game.mode==='playing'?1.3:0;this.camera.x+=(a.x+Math.cos(a.angle)*ahead-this.camera.x)*follow;this.camera.y+=(a.y+Math.sin(a.angle)*ahead-this.camera.y)*follow;const unit=Math.max(15,Math.min(31,W/43))*this.zoom;this.shake*=Math.exp(-dt*8);const sx=this.reduce?0:Math.sin(time*93)*this.shake*5,sy=this.reduce?0:Math.cos(time*79)*this.shake*4;const ox=W/2-this.camera.x*unit+sx,oy=H/2-this.camera.y*unit+sy;this.view={cell:unit,x:ox,y:oy};c.fillStyle='#dbe5ed';c.fillRect(0,0,W,H);c.save();c.translate(ox,oy);c.scale(unit,unit);c.fillStyle='#f0f5f8';c.fillRect(0,0,100,100);c.drawImage(this.land,0,0,100,100);c.strokeStyle='#a8bdcd';c.lineWidth=.14;c.strokeRect(0,0,100,100);c.strokeStyle='#ffffffbb';c.lineWidth=.12;c.strokeRect(.25,.25,99.5,99.5);
 // Subtle drifting dust is intentionally independent of any grid.
 for(let i=0;i<58;i++){const x=(i*17.39+Math.sin(time*.12+i)*.4)%100,y=(i*31.47+time*.07)%100;c.globalAlpha=.12+.07*Math.sin(time+i);c.fillStyle='#7094aa';c.beginPath();c.arc(x,y,.025+(i%3)*.012,0,Math.PI*2);c.fill()}c.globalAlpha=1;
 for(const event of game.captures){c.save();c.clip(this.paths[event.id],'evenodd');const alpha=event.life/event.max;c.fillStyle=`rgba(255,255,255,${alpha*.48})`;c.fill(this.paths[event.id],'evenodd');c.restore()}
 for(const b of game.actors)if(b.alive&&b.trail.length){const points=[...b.trail,{x:b.x,y:b.y,d:b.pathLength}],kind=b.id===1?trail:0;const line=()=>{c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y))};c.save();c.lineCap='round';c.lineJoin='round';line();c.lineWidth=.88;c.strokeStyle='#294d6b17';c.save();c.translate(0,.14);c.stroke();c.restore();if(kind===2){c.shadowColor=b.color;c.shadowBlur=18}c.lineWidth=.69;c.strokeStyle=b.color;if(kind===1){c.setLineDash([.52,.4]);c.lineDashOffset=-time*.8}if(kind===3){c.lineWidth=.73;for(let k=1;k<points.length;k++){c.beginPath();c.moveTo(points[k-1].x,points[k-1].y);c.lineTo(points[k].x,points[k].y);c.strokeStyle=`hsl(${(points[k].d*15+time*30)||0} 90% 65%)`;c.stroke()}}else{line();c.stroke()}c.shadowBlur=0;c.lineWidth=.14;c.strokeStyle='#ffffff68';line();c.stroke();c.setLineDash([]);if(kind===2){for(let k=0;k<points.length;k+=12){const p=points[k],r=.07+.05*Math.sin(time*8+k);c.fillStyle='#ffffff';c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill()}}c.restore()}
 for(const r of game.rings){const t=1-r.life/r.max;c.beginPath();c.arc(r.x,r.y,.5+Math.sin(t*Math.PI/2)*r.size,0,Math.PI*2);c.strokeStyle=r.color;c.lineWidth=.12*(1-t)+.02;c.globalAlpha=(1-t)*.7;c.stroke()}c.globalAlpha=1;c.restore();
 // Draw characters at screen scale so bevels and soft shadows stay crisp.
 for(const b of game.actors){if(!b.alive)continue;const x=ox+b.x*unit,y=oy+b.y*unit;if(x<-100||x>W+100||y<-100||y>H+100)continue;if(b.id===1){const aura=c.createRadialGradient(x,y,2,x,y,unit*1.9);aura.addColorStop(0,b.color+'25');aura.addColorStop(1,b.color+'00');c.fillStyle=aura;c.fillRect(x-unit*2,y-unit*2,unit*4,unit*4)}this.cube(c,x,y,unit*1.08,b.color,b.id===1?skin.symbol:'',b.angle,b.bank,time);if(b.shield>game.elapsed){c.beginPath();c.arc(x,y-unit*.1,unit*(.9+.035*Math.sin(time*8)),0,Math.PI*2);c.strokeStyle='#ffffffcc';c.lineWidth=2;c.setLineDash([5,4]);c.lineDashOffset=time*-12;c.stroke();c.setLineDash([])}c.font=`${b.id===1?'bold ':''}11px 'Trebuchet MS',sans-serif`;c.textAlign='center';const tw=c.measureText(b.name).width;this.rounded(c,x-tw/2-8,y-unit*1.18-12,tw+16,20,8,'#ffffffb8');c.fillStyle='#4a627c';c.fillText(b.name,x,y-unit*1.18+2);if(b.id===1&&game.mode==='playing'){c.save();c.translate(x,y);c.rotate(b.targetAngle);c.globalAlpha=.38;c.strokeStyle=b.color;c.lineCap='round';c.lineWidth=2;c.beginPath();c.moveTo(unit*1.7,-4);c.lineTo(unit*1.7+5,0);c.lineTo(unit*1.7,4);c.stroke();c.restore()}}
 for(const p of game.particles){const x=ox+p.x*unit,y=oy+p.y*unit,alpha=Math.min(1,p.life/p.max),size=p.size*unit;c.save();c.translate(x,y);c.rotate(time*(p.spin||0));c.globalAlpha=alpha;c.fillStyle=p.color;if(p.type==='star'||p.type==='spark'){c.shadowColor=p.color;c.shadowBlur=7;c.beginPath();for(let i=0;i<8;i++){const angle=i*Math.PI/4,r=i%2?size*.28:size;c.lineTo(Math.cos(angle)*r,Math.sin(angle)*r)}c.closePath();c.fill()}else this.rounded(c,-size/2,-size/2,size,size,1,p.color);c.restore()}
 const vignette=c.createRadialGradient(W/2,H/2,Math.min(W,H)*.3,W/2,H/2,Math.max(W,H)*.72);vignette.addColorStop(0,'#7d9eb300');vignette.addColorStop(1,'#5d829415');c.fillStyle=vignette;c.fillRect(0,0,W,H);this.minimap(game,W,H)}
 minimap(game,W,H){const c=this.ctx,size=W<600?92:125,x=W-size-26,y=H-size-28;this.rounded(c,x-9,y-9,size+18,size+18,19,'#ffffffcf');this.rounded(c,x,y,size,size,11,'#eaf1f6');c.save();c.beginPath();c.roundRect(x,y,size,size,11);c.clip();c.drawImage(this.land,x,y,size,size);const a=game.actors[0];c.beginPath();c.arc(x+a.x/100*size,y+a.y/100*size,4,0,Math.PI*2);c.fillStyle='#fff';c.fill();c.strokeStyle='#224565';c.lineWidth=1.7;c.stroke();c.restore()}
 menu(W,H,time){const c=this.ctx;c.fillStyle='#edf3f7';c.fillRect(0,0,W,H);const scaleX=W/1536,scaleY=H/1024;c.save();c.scale(scaleX,scaleY);const blobs=[['#50d9ec',[[0,0],[475,0]],'cyan'],['#ffb568',[], 'orange'],['#b398f5',[],'purple'],['#6ce4c0',[],'mint']];for(let i=0;i<4;i++){c.save();c.beginPath();if(i===0){c.moveTo(0,0);c.lineTo(550,0);c.bezierCurveTo(540,100,420,105,420,175);c.bezierCurveTo(425,265,258,210,230,288);c.bezierCurveTo(185,410,70,380,0,405)}if(i===1){c.moveTo(970,0);c.lineTo(1536,0);c.lineTo(1536,340);c.bezierCurveTo(1440,325,1440,390,1340,342);c.bezierCurveTo(1230,284,1330,217,1190,202);c.bezierCurveTo(1000,180,1120,74,970,65)}if(i===2){c.moveTo(0,470);c.bezierCurveTo(180,440,90,670,225,680);c.bezierCurveTo(385,690,233,824,416,835);c.bezierCurveTo(581,845,484,920,625,1024);c.lineTo(0,1024)}if(i===3){c.moveTo(1536,480);c.bezierCurveTo(1360,490,1480,668,1320,690);c.bezierCurveTo(1150,716,1300,823,1135,876);c.bezierCurveTo(1008,912,1070,970,952,1024);c.lineTo(1536,1024)}c.closePath();c.shadowColor=blobs[i][0]+'77';c.shadowBlur=36;c.shadowOffsetY=8;const g=c.createLinearGradient(0,0,1200,1000);g.addColorStop(0,this.mix(blobs[i][0],'#ffffff',.22));g.addColorStop(1,blobs[i][0]);c.fillStyle=g;c.fill();c.shadowBlur=0;c.strokeStyle='#ffffff60';c.lineWidth=3;c.stroke();c.restore()}
 const configs=[{x:370,y:285,color:'#00cbe6',phase:0},{x:1255,y:270,color:'#ffa447',phase:2.4},{x:350,y:728,color:'#a572f0',phase:4.3},{x:1230,y:768,color:'#35d4a3',phase:1.7}];configs.forEach((b,i)=>{const path=new Path2D();const p=t=>({x:b.x+Math.cos(t)*72,y:b.y+Math.sin(t)*55});const theta=time*.24+b.phase;for(let k=0;k<65;k++){const q=p(theta-2+k/32);k?path.lineTo(q.x,q.y):path.moveTo(q.x,q.y)}c.lineCap='round';c.lineWidth=17;c.strokeStyle=b.color+'79';c.shadowColor=b.color+'4a';c.shadowBlur=18;c.stroke(path);c.shadowBlur=0;c.lineWidth=3;c.strokeStyle='#ffffff60';c.stroke(path);const pos=p(theta);this.cube(c,pos.x,pos.y,44,b.color,'',theta+Math.PI/2,0,time);for(let k=0;k<5;k++){const t=theta-k*.18,q=p(t);c.globalAlpha=(1-k/5)*.6;c.fillStyle=b.color;c.beginPath();c.arc(q.x+Math.sin(time*2+k)*13,q.y+18+k*3,2,0,Math.PI*2);c.fill()}c.globalAlpha=1});for(let i=0;i<22;i++){const x=(i*431.4)%1536,y=(i*213.7+time*(i%2?3:-3)+2048)%1024;c.globalAlpha=.2+.12*Math.sin(time+i);c.fillStyle=['#02bfde','#eeb064','#a18be0','#4ac7a4'][i%4];c.save();c.translate(x,y);c.rotate(time*.12+i);c.fillRect(-4,-4,8,8);c.restore()}c.globalAlpha=1;c.restore()}
}

